export const actions = {
    profileActions: {
        DATA_FATCHING: "PROFILE_DATA_FATCHING",
        DATA_FETCHED: "PROFILE_DATA_FETCHED",
        DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
        BIO_UPDATED: "PROFILE_BIO_UPDATED",
        PROFILE_IMAGE_UPDATED: "PROFILE_PROFILE_IMAGE_UPDATED",
    },
    postActions: {
        POST_DATA_FATCHING: "POST_DATA_FATCHING",
        POST_DATA_FATCHED: "POST_DATA_FETCHED",
        POST_DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
        POST_CREATED: "POST_CREATED",
        POST_LIKED: "POST_LIKED",
        POST_COMMENTED: "POST_COMMENTED",
        POST_EDITED: "POST_EDITED",
        POST_DELETED: "POST_DELETED",
    },
};
